name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
    push:
      paths-ignore:
        - '**.md'

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
   