name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
    push:
      paths-ignore:
        - '**.md'

jobs:
  build-image:
    name: Build Docker images and push to ACR
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Nginx sidecar
      run: |
        az acr build \
          --registry ${{ secrets.ACR_NAME }} \
          --image nginx-proxy:${{ github.sha }} \
          --file ./nginx-sidecar/Dockerfile \
          ./nginx-sidecar

    - name: Build and push Flask app
      run: |
        az acr build \
          --registry ${{ secrets.ACR_NAME }} \
          --image qa-demo:${{ github.sha }} \
          --file ./flask-app/Dockerfile \
          ./flask-app

